import QtQuick 2.12
import QtQuick.Controls 2.5
import QtQuick.Window 2.0
//import QtQml.Models 2.1
import "."
import "./../images/"
ListModel{
    id:actionDelegateModel
    ListElement{
        actionName:"Home";
        homeAction:true;
        newPatientAction:true;
        existingPatientAction:true;
        testPageAction:true;
        actionIconName:"icon_home"
        actionIconSource:"qrc:/images/icon_home.png"
        actionIconColor:"transparent"
        actionImgSource:"icon_new_patient";//icon.name: "timeline_tab_selected"
        index:1;
    }
    ListElement{
        actionName:"Setting";
        homeAction:true;
        newPatientAction:true;
        existingPatientAction:true;
        testPageAction:true;
        actionIconName:"icon_setting"
        actionIconSource:"qrc:/images/icon_setting.png"
        actionIconColor:"transparent"
        actionImgSource:"icon_setting";//"../images/icon_new_patient.png";
        index:2;
    }
    ListElement{
        actionName:"Help";
        homeAction:true;
        newPatientAction:true;
        existingPatientAction:true;
        testPageAction:true;
        actionIconName:"icon_help"
        actionIconSource:"qrc:/images/icon_help.png"
        actionIconColor:"transparent"
        actionImgSource:"icon_help";//"../images/icon_new_patient.png";
        index:3;
    }
    ListElement{
        actionName:"changePatient";
        //homeAction:false;
        newPatientAction:true;
        //existingPatientAction:true;
        testPageAction:true;
        actionIconName:"icon_switch_patient"
        actionIconSource:"qrc:/images/icon_switch_patient.png"
        actionIconColor:"transparent"
        actionImgSource:"icon_switch_patient";//"../images/icon_new_patient.png";
        index:4;
    }
    ListElement{
        actionName:"savePatient";
        //homeAction:false;
        newPatientAction:true;
        //existingPatientAction:true;
        //testPageAction:true;
        actionIconName:"icon_save"
        actionIconSource:"qrc:/images/icon_save.png"
        actionIconColor:"transparent"
        actionImgSource:"icon_save";//"../images/icon_new_patient.png";
        index:5;
    }
    ListElement{
        actionName:"testPatient";
        //homeAction:false;
        newPatientAction:true;
        existingPatientAction:true;
        //testPageAction:true;
        actionIconName:"icon_test_patient"
        actionIconSource:"qrc:/images/icon_test_patient.png"
        actionIconColor:"transparent"
        actionImgSource:"icon_test_patient";//"../images/icon_new_patient.png";
        index:6;
    }
    ListElement{
        actionName:"newPatient";
        //homeAction:false;
        //newPatientAction:true;
        existingPatientAction:true;
        //testPageAction:true;
        actionIconName:"icon_new_patient"
        actionIconSource:"qrc:/images/icon_new_patient.png"
        actionIconColor:"transparent"
        actionImgSource:"../images/icon_new_patient.png";
        index:7;
    }
    ListElement{
        actionName:"editPatient";
        //homeAction:false;
        //newPatientAction:true;
        existingPatientAction:true;
        testPageAction:true;
        actionIconName:"icon_edit_patient"
        actionIconSource:"qrc:/images/icon_edit_patient.png"
        actionIconColor:"transparent"
        actionImgSource:"../images/icon_new_patient.png";
        index:8;
    }
    ListElement{
        actionName:"viewPatientReport";
        //homeAction:false;
        //newPatientAction:true;
        //existingPatientAction:true;
        testPageAction:true;
        reportPageAction:true;
        actionIconName:"icon_view_report"
        actionIconSource:"qrc:/images/icon_view_report.png"
        actionIconColor:"transparent"
        actionImgSource:"../images/icon_new_patient.png";
        index:9;
    }
    ListElement{
        actionName:"addOperator";
        //homeAction:false;
        //newPatientAction:true;
        //existingPatientAction:true;
        //testPageAction:true;
        //reportPageAction:true;
        operatorPageAction:true;
        actionIconName:"icon_add_operator"
        actionIconSource:"qrc:/images/icon_add_operator.png"
        actionIconColor:"transparent"
        actionImgSource:"../images/icon_new_patient.png";
        index:10;
    }
    ListElement{
        actionName:"editOperator";
        //homeAction:false;
        //newPatientAction:true;
        //existingPatientAction:true;
        //testPageAction:true;
        //reportPageAction:true;
        operatorPageAction:true;
        actionIconName:"icon_edit_operator"
        actionIconSource:"qrc:/images/icon_edit_operator.png"
        actionIconColor:"transparent"
        //actionImgSource:"../images/icon_new_patient.png";
        actionImgSource:"icon_new_patient";//"../images/icon_new_patient.png";
        index:11;
    }
}
